name: Publish Docker images

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 1 * *"

jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            dennistt/gpx2video
            ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix={{branch}}-,suffix=-{{date 'YYYYMMDD-hhmmss' tz='America/Vancouver'}},priority=1000
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
